spring.application.name=api

//spring.application.name=campus-reserve

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_reserve
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET:CD3Jvf99npTAATwjTWn1qoaOvr2DyC9RRJBkYSSPxqw=}
security.jwt.issuer=campus-reserve-api
security.jwt.expiration-seconds=3600

app.initial-admin.enabled=${INITIAL_ADMIN_ENABLED:false}
app.initial-admin.name=${INITIAL_ADMIN_NAME:Administrador}
app.initial-admin.email=${INITIAL_ADMIN_EMAIL:}
app.initial-admin.password=${INITIAL_ADMIN_PASSWORD:}